resource_group_name    = "kv_terraform_rg"
location               = "West Europe"
keyvault_name          = "vilasdemo010901"
secret_name            = "VilasSecretName1"
secret_value           = "@Aa123456789!"