resource_group_name    = "kv_terraform_rg"
location               = "West Europe"
keyvault_name          = "vilasdemo01090"
secret_name            = "VilasSecretName"
secret_value           = "@Aa123456789!"